### ISSUE TITLE
思いつく改善可能箇所

### ISSUE THREAD

**Issue by ahy4** [ahy4/dotfiles#1]
簡単なものだけでも

* vim の color theme どうするか考える。現状はターミナルのカラーを尊重している
* rangerを使う
* vim UltiSnips fugitive.vim

**Comment by ahy4** [comment]
git系はもうちょっといい感じにgit側からやりたい
fzfだけしかいれてないので、ファイル作る際消す際はちょっと手間になってる

**Comment by ahy4** [comment]
easymotionくらいあってもいいかもね

**Comment by ahy4** [comment]
easymotion試してみたけどライブラリとしてデカすぎでしょ。vim-sneakにした

**Comment by yuya-sato-geniee** [comment]
rangerは横幅が狭いとファイル名が省略されてしまって、みにくい。

容量とかupdateされた日付を省略すべき

**Comment by yuya-sato-geniee** [comment]
そういえばこれimeの設定入ってなくね？

**Comment by yuya-sato-geniee** [comment]
rangerは便利だけど純粋に起動がおそいね。shellを開いてるからなら、高速化すべき

**Comment by ahy4** [comment]
なんか同じbufferを開いてるときのvaffleおかしいくね？なんでだろう。最近バグが追加されたのかな

https://youtu.be/JBVTGzSZC3s

**Comment by ahy4** [comment]
vimにおいて、横幅が20文字未満なら折返しせず、以上なら折返しをしたい

**Comment by ahy4** [comment]
statusline、境界がわかるようにしたい
